# Generated by Django 5.0.6 on 2024-07-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_customer_name_alter_order_menu_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='menu_id',
            new_name='menu_item',
        ),
    ]
